### ISSUE TITLE
The datapack for version 1.21 does not work

### ISSUE THREAD

**Issue by Evgenii733** [tayadev/Invisible-Item-Frames#4]
The invisible frame is not being crafted at all.The datapack does not work on version 1.21

**Comment by Evgenii733** [comment]
Have you fixed it?

**Comment by tayacrystals** [comment]
not yet, once i get around to fixing it and have fixed it i will close the issue and mark it as solved

**Comment by Evgenii733** [comment]
The developer of the datapack, how soon will you release the 1.21 version of the datapack?

**Comment by tayacrystals** [comment]
I'll get around to it by the weekend

**Comment by tayacrystals** [comment]
Updated it
